# Cirrus CI configuration for go-l10n
# Testing on Linux and FreeBSD with multiple architectures

# FreeBSD 13 - AMD64
freebsd_13_amd64_task:
  name: FreeBSD 13 AMD64
  freebsd_instance:
    image_family: freebsd-13-3
  env:
    GO_VERSION: go1.23.4
  install_script:
    - pkg install -y go
  test_script:
    - go version
    - go mod download
    - go test -v ./...

# FreeBSD 13 - ARM64
freebsd_13_arm64_task:
  name: FreeBSD 13 ARM64
  arm_container:
    image: freebsd:13.3-RELEASE
  env:
    GO_VERSION: go1.23.4
  install_script:
    - pkg install -y go
  test_script:
    - go version
    - go mod download
    - go test -v ./...

# FreeBSD 14 - AMD64
freebsd_14_amd64_task:
  name: FreeBSD 14 AMD64
  freebsd_instance:
    image_family: freebsd-14-0
  env:
    GO_VERSION: go1.23.4
  install_script:
    - pkg install -y go
  test_script:
    - go version
    - go mod download
    - go test -v ./...

# FreeBSD 14 - ARM64
freebsd_14_arm64_task:
  name: FreeBSD 14 ARM64
  arm_container:
    image: freebsd:14.0-RELEASE
  env:
    GO_VERSION: go1.23.4
  install_script:
    - pkg install -y go
  test_script:
    - go version
    - go mod download
    - go test -v ./...

# Linux - Ubuntu (latest LTS)
linux_ubuntu_task:
  name: Linux Ubuntu 22.04
  container:
    image: golang:1.23-bullseye
  test_script:
    - go version
    - go mod download
    - go test -v ./...

# Linux - Alpine (lightweight)
linux_alpine_task:
  name: Linux Alpine
  container:
    image: golang:1.23-alpine
  test_script:
    - go version
    - go mod download
    - go test -v ./...

# Linux - Debian
linux_debian_task:
  name: Linux Debian
  container:
    image: golang:1.23-bookworm
  test_script:
    - go version
    - go mod download
    - go test -v ./...

# Linux - CentOS Stream
linux_centos_task:
  name: Linux CentOS Stream
  container:
    image: quay.io/centos/centos:stream9
  install_script:
    - dnf install -y golang
  test_script:
    - go version
    - go mod download
    - go test -v ./...

# Linux ARM64
linux_arm64_task:
  name: Linux ARM64
  arm_container:
    image: golang:1.23-bullseye
  test_script:
    - go version
    - go mod download
    - go test -v ./...

